### ISSUE TITLE
Paper subtitles are not showing up

### ISSUE THREAD

**Issue by jdavies-st** [mfouesneau/arxiv_on_deck_2#19]
The Euclid A&A format often includes

```latex
\title{\Euclid preparation}
\subtitle{We simulated some stuff}
```

Currently the subtitle is not showing up in the output Markdown.

**Comment by mfouesneau** [comment]
weird, because it should be parsed:
https://github.com/mfouesneau/arxiv_on_deck_2/blob/34cacb34d56db846c83831327e5a219eb65af9b0/arxiv_on_deck_2/latex.py#L768

**Comment by jdavies-st** [comment]
I think I have a fix for this. PR forthcoming.
